### ISSUE TITLE
Recognition of T212 export differentiation between GBp(pence) vs. GBP(pound)

### ISSUE THREAD

**Issue by WouterSuijker** [dickwolff/Export-To-Ghostfolio#23]
In my T212 export file there are some assets listed in GBpence instead of GBpound. For this reason some transactions are multipled by 100 which really screws up the charts. Is it possible to recognize the difference between GBp vs GBP and adjust the currency accordingly?

**Comment by dickwolff** [comment]
One think to check, you do have GBp as a currency in Ghostfolio? Like the screenshot below?

![Ghostfolio Admin Panel](https://github.com/dickwolff/Export-To-Ghostfolio/assets/5620002/9d186c95-1b95-4cd3-9c3d-447b73e191a9)

I have seen this issue before but with `GBp` seen as `GBx` and have since fixed that by replacing the `x` with an `p` which resolved my issues back then.

**Comment by WouterSuijker** [comment]
GBp was missing, it's working as expected now. Thanks for the info.
