### ISSUE TITLE
GBX items are not imported correctly

### ISSUE THREAD

**Issue by fugkco** [dickwolff/Export-To-Ghostfolio#93]
I've some items imported as GBX. I've got a GBp currency added, but I get the following error:

```
activities.6.currency ("GBP") does not match with currency of AV.L ("GBp")
```

To get it to import correctly (at least I think it's correct?), I transform the json file using the following jq query:

```
(.activities | [.[] | if .currency == "GBP" then .currency = "GBp" | .unitPrice = (.unitPrice*100) else . end])
```

That is, for all items where `currency == "GBP"`, set `currency = "GBp"` and `unitPrice = unitPrice*100`.

Am I doing something wrong, or is there a bug in the system?

Example CSV record:
```
Date,Time,Value date,Product,ISIN,Description,FX,Change,,Balance,,Order Id
02-04-2024,09:00,02-04-2024,AVIVA,GB00BPQY8M80,Sell 4 AVIVA@496 GBX (GB00BPQY8M80),,GBP,19.84,GBP,114.31,86c1f17b-8a74-4126-af39-61049bcb6e33
```

**Comment by dickwolff** [comment]
Hi there! Sorry for the late response as I've been busy.

The security service has a catch-all for `GBP` which you can find [here](https://github.com/dickwolff/Export-To-Ghostfolio/blob/d45da7e3d11945790002ac0410e918ea62567dda/src/securityService.ts#L91). When you have a GBP and there is no match, it looks for a `GBp` variant. The stock you mention (`AV.L`) has a [GBp](https://finance.yahoo.com/quote/AV.L/) notation on Yahoo Finance. So it looks like the tool found the right one. 

Maybe the return of this is wrong, however. I don't know which converter you're using (can't seem to find it in your bug report), but I think the issue is I'm not using the resulting currency (so if your export says `GBP` and we've found a `GBp`, maybe it still puts `GBP` in the resulting JSON.
 
Can you let me know which converter this is, and maybe give me the line from your export so I can verify this locally? Thanks!

**Comment by fugkco** [comment]
Oh, sorry, that error is from Ghostfolio itself. This specific transaction comes from De Giro. The output json:

```json
{
  "activities": [
    {
      "accountId": "98ab2695-a513-4346-9836-8b4f70a15544",
      "comment": "",
      "currency": "GBP",
      "dataSource": "YAHOO",
      "date": "2024-04-02T09:00:00+00:00",
      "fee": 0,
      "quantity": 4,
      "symbol": "AV.L",
      "type": "SELL",
      "unitPrice": 4.96
    }
  ],
  "meta": {
    "date": "2024-07-31T07:13:14.130Z",
    "version": "v0"
  },
  "updateCashBalance": false
}
```

**Comment by dickwolff** [comment]
This confirms my suspicion about putting the wrong currency in the result. Will try and make a fix later this week and get back to you.

**Comment by dickwolff** [comment]
I have made a possible fix, and also added a test case to the DEGIRO service to verify it's working. 

Could you try it out using the [beta image](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.16.3-beta/images/sha256-8caef536ae0cbbf7c9ee872bfb131a2bd74e72685e867102da51461ab0e90622)?

If this works, then I'll probably bump this change to all other converters as well, as I think this is an issue that could appear at all converters, not just DEGIRO.

**Comment by fugkco** [comment]
That worked! Thank you!

**Comment by dickwolff** [comment]
Great to hear! I will merge #99 and update all other converters in a separate PR.
